[2021-12-15 19:54:47,316] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: run_test_db.test_database manual__2021-12-15T19:54:46.620350+00:00 [queued]>
[2021-12-15 19:54:47,330] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: run_test_db.test_database manual__2021-12-15T19:54:46.620350+00:00 [queued]>
[2021-12-15 19:54:47,330] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-15 19:54:47,330] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-15 19:54:47,330] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-15 19:54:47,342] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): test_database> on 2021-12-15 19:54:46.620350+00:00
[2021-12-15 19:54:47,349] {standard_task_runner.py:52} INFO - Started process 12786 to run task
[2021-12-15 19:54:47,353] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'run_test_db', 'test_database', 'manual__2021-12-15T19:54:46.620350+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/test-mssq-conn.py', '--cfg-path', '/tmp/tmpj7xc26t1', '--error-file', '/tmp/tmp5k9qgsnw']
[2021-12-15 19:54:47,354] {standard_task_runner.py:77} INFO - Job 43: Subtask test_database
[2021-12-15 19:54:47,398] {logging_mixin.py:109} INFO - Running <TaskInstance: run_test_db.test_database manual__2021-12-15T19:54:46.620350+00:00 [running]> on host 438190b6391d
[2021-12-15 19:54:47,458] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=example@email.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=run_test_db
AIRFLOW_CTX_TASK_ID=test_database
AIRFLOW_CTX_EXECUTION_DATE=2021-12-15T19:54:46.620350+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-15T19:54:46.620350+00:00
[2021-12-15 19:54:47,485] {logging_mixin.py:109} INFO -                          table_name
0                          ErrorLog
1                      BuildVersion
2                           Address
3                          Customer
4                   CustomerAddress
5                           Product
6                   ProductCategory
7                ProductDescription
8                      ProductModel
9    ProductModelProductDescription
10                 SalesOrderDetail
11                 SalesOrderHeader
12           vProductAndDescription
13  vProductModelCatalogDescription
14                vGetAllCategories
[2021-12-15 19:54:47,486] {python.py:152} INFO - Done. Returned value was:                          table_name
0                          ErrorLog
1                      BuildVersion
2                           Address
3                          Customer
4                   CustomerAddress
5                           Product
6                   ProductCategory
7                ProductDescription
8                      ProductModel
9    ProductModelProductDescription
10                 SalesOrderDetail
11                 SalesOrderHeader
12           vProductAndDescription
13  vProductModelCatalogDescription
14                vGetAllCategories
[2021-12-15 19:54:47,514] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=run_test_db, task_id=test_database, execution_date=20211215T195446, start_date=20211215T195447, end_date=20211215T195447
[2021-12-15 19:54:47,565] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-15 19:54:47,595] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
