[2021-12-14 08:05:21,419] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.populate_pet_table manual__2021-12-14T08:05:19.119259+00:00 [queued]>
[2021-12-14 08:05:21,430] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.populate_pet_table manual__2021-12-14T08:05:19.119259+00:00 [queued]>
[2021-12-14 08:05:21,430] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-14 08:05:21,430] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-14 08:05:21,430] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-14 08:05:21,442] {taskinstance.py:1262} INFO - Executing <Task(PostgresOperator): populate_pet_table> on 2021-12-14 08:05:19.119259+00:00
[2021-12-14 08:05:21,451] {standard_task_runner.py:52} INFO - Started process 791 to run task
[2021-12-14 08:05:21,455] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'populate_pet_table', 'manual__2021-12-14T08:05:19.119259+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/pets_dag.py', '--cfg-path', '/tmp/tmppg4xhe3v', '--error-file', '/tmp/tmpvely_9ap']
[2021-12-14 08:05:21,455] {standard_task_runner.py:77} INFO - Job 25: Subtask populate_pet_table
[2021-12-14 08:05:21,496] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_operator_dag.populate_pet_table manual__2021-12-14T08:05:19.119259+00:00 [running]> on host 4ee0ea791fc7
[2021-12-14 08:05:21,550] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_operator_dag
AIRFLOW_CTX_TASK_ID=populate_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2021-12-14T08:05:19.119259+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-14T08:05:19.119259+00:00
[2021-12-14 08:05:21,560] {base.py:79} INFO - Using connection to: id: ***_conn_id. Host: postgres-***, Port: 5432, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-14 08:05:21,564] {dbapi.py:225} INFO - Running statement: -- populate pet table
INSERT INTO pet (name, pet_type, birth_date, OWNER)
VALUES ( 'Max', 'Dog', '2018-07-05', 'Jane');
INSERT INTO pet (name, pet_type, birth_date, OWNER)
VALUES ( 'Susie', 'Cat', '2019-05-01', 'Phil');
INSERT INTO pet (name, pet_type, birth_date, OWNER)
VALUES ( 'Lester', 'Hamster', '2020-06-23', 'Lily');
INSERT INTO pet (name, pet_type, birth_date, OWNER)
VALUES ( 'Quincy', 'Parrot', '2013-08-11', 'Anne');, parameters: None
[2021-12-14 08:05:21,566] {dbapi.py:233} INFO - Rows affected: 1
[2021-12-14 08:05:21,583] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=postgres_operator_dag, task_id=populate_pet_table, execution_date=20211214T080519, start_date=20211214T080521, end_date=20211214T080521
[2021-12-14 08:05:21,627] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-14 08:05:21,660] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
