[2021-12-14 07:31:43,446] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.populate_pet_table manual__2021-12-14T07:31:41.431384+00:00 [queued]>
[2021-12-14 07:31:43,457] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.populate_pet_table manual__2021-12-14T07:31:41.431384+00:00 [queued]>
[2021-12-14 07:31:43,457] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-14 07:31:43,457] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-14 07:31:43,457] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-14 07:31:43,469] {taskinstance.py:1262} INFO - Executing <Task(PostgresOperator): populate_pet_table> on 2021-12-14 07:31:41.431384+00:00
[2021-12-14 07:31:43,474] {standard_task_runner.py:52} INFO - Started process 461 to run task
[2021-12-14 07:31:43,478] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'populate_pet_table', 'manual__2021-12-14T07:31:41.431384+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/pets_dag.py', '--cfg-path', '/tmp/tmp_t7620pm', '--error-file', '/tmp/tmp0o2bcex9']
[2021-12-14 07:31:43,479] {standard_task_runner.py:77} INFO - Job 8: Subtask populate_pet_table
[2021-12-14 07:31:43,521] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_operator_dag.populate_pet_table manual__2021-12-14T07:31:41.431384+00:00 [running]> on host 45fc176cd679
[2021-12-14 07:31:43,573] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_operator_dag
AIRFLOW_CTX_TASK_ID=populate_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2021-12-14T07:31:41.431384+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-14T07:31:41.431384+00:00
[2021-12-14 07:31:43,582] {base.py:79} INFO - Using connection to: id: ***_conn_id. Host: postgres-***, Port: 5432, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-14 07:31:43,586] {dbapi.py:225} INFO - Running statement: -- populate pet table
INSERT INTO pet (name, pet_type, birth_date, OWNER)
VALUES ( 'Max', 'Dog', '2018-07-05', 'Jane');
INSERT INTO pet (name, pet_type, birth_date, OWNER)
VALUES ( 'Susie', 'Cat', '2019-05-01', 'Phil');
INSERT INTO pet (name, pet_type, birth_date, OWNER)
VALUES ( 'Lester', 'Hamster', '2020-06-23', 'Lily');
INSERT INTO pet (name, pet_type, birth_date, OWNER)
VALUES ( 'Quincy', 'Parrot', '2013-08-11', 'Anne');, parameters: None
[2021-12-14 07:31:43,588] {dbapi.py:233} INFO - Rows affected: 1
[2021-12-14 07:31:43,605] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=postgres_operator_dag, task_id=populate_pet_table, execution_date=20211214T073141, start_date=20211214T073143, end_date=20211214T073143
[2021-12-14 07:31:43,650] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-14 07:31:43,684] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
