[2021-12-13 20:43:04,551] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.populate_pet_table manual__2021-12-13T20:43:03.557339+00:00 [queued]>
[2021-12-13 20:43:04,579] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.populate_pet_table manual__2021-12-13T20:43:03.557339+00:00 [queued]>
[2021-12-13 20:43:04,579] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-13 20:43:04,580] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-13 20:43:04,580] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-13 20:43:04,608] {taskinstance.py:1262} INFO - Executing <Task(PostgresOperator): populate_pet_table> on 2021-12-13 20:43:03.557339+00:00
[2021-12-13 20:43:04,635] {standard_task_runner.py:52} INFO - Started process 3696 to run task
[2021-12-13 20:43:04,640] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'populate_pet_table', 'manual__2021-12-13T20:43:03.557339+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/example_postgres.py', '--cfg-path', '/tmp/tmpzzwx0qy5', '--error-file', '/tmp/tmphc7i4o79']
[2021-12-13 20:43:04,641] {standard_task_runner.py:77} INFO - Job 18: Subtask populate_pet_table
[2021-12-13 20:43:04,721] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_operator_dag.populate_pet_table manual__2021-12-13T20:43:03.557339+00:00 [running]> on host ef07609851a1
[2021-12-13 20:43:04,795] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_operator_dag
AIRFLOW_CTX_TASK_ID=populate_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2021-12-13T20:43:03.557339+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-13T20:43:03.557339+00:00
[2021-12-13 20:43:04,805] {base.py:79} INFO - Using connection to: id: postgres_***_db. Host: postgres-***, Port: 5432, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-13 20:43:04,811] {dbapi.py:225} INFO - Running statement: 
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Max', 'Dog', '2018-07-05', 'Jane');
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Susie', 'Cat', '2019-05-01', 'Phil');
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Lester', 'Hamster', '2020-06-23', 'Lily');
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Quincy', 'Parrot', '2013-08-11', 'Anne');
            , parameters: None
[2021-12-13 20:43:04,813] {dbapi.py:233} INFO - Rows affected: 1
[2021-12-13 20:43:04,830] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=postgres_operator_dag, task_id=populate_pet_table, execution_date=20211213T204303, start_date=20211213T204304, end_date=20211213T204304
[2021-12-13 20:43:04,859] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-13 20:43:04,924] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
