[2021-12-14 07:27:29,522] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.hook_task manual__2021-12-14T07:27:26.993362+00:00 [queued]>
[2021-12-14 07:27:29,534] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.hook_task manual__2021-12-14T07:27:26.993362+00:00 [queued]>
[2021-12-14 07:27:29,535] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-14 07:27:29,535] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-14 07:27:29,535] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-14 07:27:29,548] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): hook_task> on 2021-12-14 07:27:26.993362+00:00
[2021-12-14 07:27:29,553] {standard_task_runner.py:52} INFO - Started process 281 to run task
[2021-12-14 07:27:29,558] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'hook_task', 'manual__2021-12-14T07:27:26.993362+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/pets_dag.py', '--cfg-path', '/tmp/tmpogucgjjn', '--error-file', '/tmp/tmp0anl2zj9']
[2021-12-14 07:27:29,558] {standard_task_runner.py:77} INFO - Job 6: Subtask hook_task
[2021-12-14 07:27:29,603] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_operator_dag.hook_task manual__2021-12-14T07:27:26.993362+00:00 [running]> on host 45fc176cd679
[2021-12-14 07:27:29,658] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_operator_dag
AIRFLOW_CTX_TASK_ID=hook_task
AIRFLOW_CTX_EXECUTION_DATE=2021-12-14T07:27:26.993362+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-14T07:27:26.993362+00:00
[2021-12-14 07:27:29,668] {base.py:79} INFO - Using connection to: id: ***_conn_id. Host: postgres-***, Port: 5432, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-14 07:27:29,673] {logging_mixin.py:109} INFO - source: {0} - activated: {1}
[2021-12-14 07:27:29,673] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pets_dag.py", line 17, in get_all_pets
    print("source: {0} - activated: {1}").format(source[0], source[1])
AttributeError: 'NoneType' object has no attribute 'format'
[2021-12-14 07:27:29,689] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=postgres_operator_dag, task_id=hook_task, execution_date=20211214T072726, start_date=20211214T072729, end_date=20211214T072729
[2021-12-14 07:27:29,705] {standard_task_runner.py:91} ERROR - Failed to execute job 6 for task hook_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pets_dag.py", line 17, in get_all_pets
    print("source: {0} - activated: {1}").format(source[0], source[1])
AttributeError: 'NoneType' object has no attribute 'format'
[2021-12-14 07:27:29,729] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-14 07:27:29,760] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
