[2021-12-15 12:31:24,966] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: example_mssql.create_country_table manual__2021-12-15T12:31:23.480469+00:00 [queued]>
[2021-12-15 12:31:24,978] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: example_mssql.create_country_table manual__2021-12-15T12:31:23.480469+00:00 [queued]>
[2021-12-15 12:31:24,978] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-15 12:31:24,978] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-15 12:31:24,978] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-15 12:31:24,991] {taskinstance.py:1262} INFO - Executing <Task(MsSqlOperator): create_country_table> on 2021-12-15 12:31:23.480469+00:00
[2021-12-15 12:31:24,997] {standard_task_runner.py:52} INFO - Started process 250 to run task
[2021-12-15 12:31:25,001] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'example_mssql', 'create_country_table', 'manual__2021-12-15T12:31:23.480469+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/example_mssql.py', '--cfg-path', '/tmp/tmpi8embwdq', '--error-file', '/tmp/tmpmb3j489p']
[2021-12-15 12:31:25,002] {standard_task_runner.py:77} INFO - Job 37: Subtask create_country_table
[2021-12-15 12:31:25,051] {logging_mixin.py:109} INFO - Running <TaskInstance: example_mssql.create_country_table manual__2021-12-15T12:31:23.480469+00:00 [running]> on host 33d3e3f0a6de
[2021-12-15 12:31:25,123] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_mssql
AIRFLOW_CTX_TASK_ID=create_country_table
AIRFLOW_CTX_EXECUTION_DATE=2021-12-15T12:31:23.480469+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-15T12:31:23.480469+00:00
[2021-12-15 12:31:25,123] {mssql.py:90} INFO - Executing: 
    CREATE TABLE Country (
        country_id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
        name TEXT,
        continent TEXT
    );
    
[2021-12-15 12:31:25,151] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/microsoft/mssql/operators/mssql.py", line 91, in execute
    hook = self.get_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/microsoft/mssql/operators/mssql.py", line 81, in get_hook
    conn = MsSqlHook.get_connection(conn_id=self.mssql_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 68, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 410, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `***_mssql` isn't defined
[2021-12-15 12:31:25,159] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=example_mssql, task_id=create_country_table, execution_date=20211215T123123, start_date=20211215T123124, end_date=20211215T123125
[2021-12-15 12:31:25,176] {standard_task_runner.py:91} ERROR - Failed to execute job 37 for task create_country_table
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/microsoft/mssql/operators/mssql.py", line 91, in execute
    hook = self.get_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/microsoft/mssql/operators/mssql.py", line 81, in get_hook
    conn = MsSqlHook.get_connection(conn_id=self.mssql_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 68, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 410, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `***_mssql` isn't defined
[2021-12-15 12:31:25,213] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-15 12:31:25,260] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
